CREATE TABLE S_MEMBER(
    ID VARCHAR2(20),
    PW VARCHAR2(40) NOT NULL,
    NICK VARCHAR2(40) NOT NULL,
    AGE NUMBER(3) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CONSTRAINT S_MEMBER_PK PRIMARY KEY(ID),
    CONSTRAINT S_MEMBER_UK_EMAIL UNIQUE(EMAIL)
);

INSERT INTO S_MEMBER VALUES('mcmh', '1234', '김얗마', 28, 'mcmh55@naver.com');
INSERT INTO S_MEMBER VALUES('1', '1', '띠용', 1, 'mcmh55@naver.com');

SELECT * FROM S_MEMBER;

SELECT ID FROM S_MEMBER WHERE ID = 1;

SELECT PW FROM S_MEMBER WHERE ID = 'mcmh';

SELECT NICK FROM S_MEMBER WHERE NICK = '1';

DELETE FROM S_MEMBER WHERE ID = 'test';

DROP TABLE S_MEMBER
CASCADE CONSTRAINTS;