-- 휴지통 비우기 --

PURGE RECYCLEBIN;

-- 회원 --

CREATE TABLE MY_MEMBER(
	M_ID	VARCHAR2(20),
	M_PW	VARCHAR2(40) NOT NULL,
	M_NICK	VARCHAR2(40) NOT NULL,
	M_AGE	NUMBER(3) NOT NULL,
	M_EMAIL	VARCHAR2(100) NOT NULL,
	CONSTRAINT MY_MEMBER_PK PRIMARY KEY(M_ID),
	CONSTRAINT MY_MEMBER_UK_EMAIL UNIQUE(M_EMAIL)
);

SELECT * FROM MY_MEMBER;

DROP TABLE MY_MEMBER
CASCADE CONSTRAINTS;


-- /////////////////////////////////////////// --

-- 게시판 --

CREATE TABLE MY_BOARD(
	B_SEQ			NUMBER,
	B_GROUP			NUMBER(2) NOT NULL,
	B_DEPTH			NUMBER(2) NOT NULL,
	B_STEP			NUMBER(2) NOT NULL,
	B_PARENT_SEQ	NUMBER NOT NULL,
	B_PARENT_DEL	NUMBER(1) NOT NULL,
	B_ID			NVARCHAR2(20) NOT NULL,
	B_PW			NUMBER(4) NOT NULL,
	B_TITLE			NVARCHAR2(50) NOT NULL,
	B_CONTENT		NCLOB NOT NULL,
	B_FILENAME		NVARCHAR2(20),
	B_READCOUNT		NUMBER NOT NULL,
	B_WRITEDATE		DATE NOT NULL,
	B_NOTICE		NUMBER(1) NOT NULL,
	B_DEL			NUMBER(1) NOT NULL,
	CONSTRAINT MY_BOARD_PK PRIMARY KEY(B_SEQ)
);

CREATE SEQUENCE SEQ_MY_BOARD
START WITH 1 INCREMENT BY 1;

DROP TABLE MY_BOARD
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MY_BOARD;

SELECT * FROM MY_BOARD ORDER BY B_GROUP DESC, B_DEPTH ASC, B_STEP ASC, B_SEQ DESC;

SELECT NVL2(MAX(B_STEP), MAX(B_STEP)+1, 0) FROM MY_BOARD 
WHERE B_GROUP = (SELECT B_GROUP FROM MY_BOARD WHERE B_SEQ = 1)
AND B_DEPTH = (SELECT B_DEPTH FROM MY_BOARD WHERE B_SEQ = 1) + 1;

SELECT * FROM MY_BOARD
WHERE B_DEL = 0
AND B_TITLE LIKE '%안녕%'
OR B_CONTENT LIKE '%안녕%';

SELECT * FROM MY_BOARD
WHERE B_CONTENT LIKE %CHR(10)%;

SELECT REPLACE(B_CONTENT, CHR(10), '<br/>') FROM MY_BOARD;

INSERT INTO MY_BOARD
VALUES(SEQ_MY_BOARD.NEXTVAL,
(SELECT B_GROUP FROM MY_BOARD WHERE B_SEQ = 1),
(SELECT B_DEPTH FROM MY_BOARD WHERE B_SEQ = 1)+1,
(SELECT NVL((SELECT B_STEP FROM MY_BOARD WHERE B_GROUP = 1 AND B_DEPTH = 1), 0)+1 FROM MY_BOARD),
1, 'test', '2', '답글', '답글이당', null, 0, SYSDATE, 0, 0, 0);

INSERT INTO MY_BOARD
VALUES(SEQ_MY_BOARD.NEXTVAL, SEQ_MY_BOARD.CURRVAL, 0, 0, 0, 0, 'test', 2, '우아아아', '캬캬', NULL, 0, SYSDATE-1, 0, 0, 0);


-- /////////////////////////////////////////// --

-- 게시판 댓글 --

CREATE TABLE MY_BOARD_COMMENT(
	BC_SEQ			NUMBER,
	BC_GROUP		NUMBER(2) NOT NULL,
	BC_DEPTH		NUMBER(2) NOT NULL,
	BC_STEP			NUMBER(2) NOT NULL,
	BC_PARENT_SEQ	NUMBER NOT NULL,
	BC_BOARD_SEQ	NUMBER NOT NULL,
	BC_ID			NVARCHAR2(20) NOT NULL,
	BC_CONTENT		NVARCHAR2(200) NOT NULL,
	BC_WRITEDATE	DATE NOT NULL,
	BC_DEL			NUMBER(1) NOT NULL,
	CONSTRAINT MY_BOARD_COMENT_PK PRIMARY KEY(BC_SEQ)
);

CREATE SEQUENCE SEQ_MY_BOARD_COMMENT
START WITH 1 INCREMENT BY 1;

DROP TABLE MY_BOARD_COMMENT
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MY_BOARD_COMMENT;

SELECT * FROM MY_BOARD_COMMENT ORDER BY BC_GROUP ASC, BC_WRITEDATE ASC;

SELECT REPLACE(BC_CONTENT,  CHR(13)||CHR(10), '야!ㅁㅁㄴㅇㅁㄴ') FROM MY_BOARD_COMMENT;